// must install "docker pipeline" and "junit" plugin

node {
    checkout scm
    stage('Build') {
        docker.image('python:2-alpine').withRun {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        try {
            docker.image('qnib/pytest').withRun {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        } catch (e) {

        } finally {
            // post always
            junit 'test-reports/results.xml'
        }
    }
    stage('Deliver') {
        docker.image('cdrx/pyinstaller-linux:python2').withRun {
            sh 'pyinstaller --onefile sources/add2vals.py'
        }

        // post success
        archiveArtifacts 'dist/add2vals'
    }
}
