node {
    stage('Build') {
        sh 'docker run python:2-alpine'
        sh 'python -m py_compile sources/add2vals.py sources/calc.py'
    }
    stage('Test') {
        try {
            sh 'docker run qnib/pytest'
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        } catch (e) {

        } finally {
            // post always
            junit 'test-reports/results.xml'
        }
    }
    stage('Deliver') {
        try {
            sh 'docker run cdrx/pyinstaller-linux:python2'
            sh 'pyinstaller --onefile sources/add2vals.py'

            // post success
            archiveArtifacts 'dist/add2vals'
        } catch (e) {

        }
    }
}
